### ISSUE TITLE
Feature suggestion: Support Javascript-formatted JSON

### ISSUE THREAD

**Issue by kodikos** [lengmoXXL/vscode-json-table-viewer#1]
If you're doing a lot of work in Javascript, you tend to get JSON outputted in Javascript format, i.e.
```javascript
[
  { field1: 'somevalue', field2: 'anothervalue' },
  { field1: 'morevalue', field2: 'anothermorevalue' }
]
```

**Comment by lengmoXXL** [comment]
It sounds good and I didn't consider it. But I found that JSON5 can do the parse, so it is already supported. You can create a xxx.js file that containing such Javascript-formatted JSON, and then call Open View command.
